source 'https://rubygems.org'

# Kept in step with the parent Gemfile so the dummy app and the gem's own dev
# dependencies resolve to the same Rails. CI sets this per matrix entry.
rails_version = ENV.fetch('RAILS_VERSION', '7.2')

gem 'cssbundling-rails', '~> 1.4'
gem 'dfe-wizard', path: '../../'
gem 'govuk-components'
gem 'govuk_design_system_formbuilder'
gem 'jsbundling-rails', '~> 1.3'
# json 3 removed options ActiveSupport 7.2 still passes (quirks_mode).
gem 'json', '< 3'
gem 'pg', '~> 1.6', '>= 1.6.2'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', "~> #{rails_version}.0"
gem 'sqlite3'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'factory_bot'
  gem 'faker'
  gem 'foreman'
  gem 'pry'
  gem 'railties', "~> #{rails_version}.0"
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails'
  gem 'rubocop', '~> 1.21'
end
