default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOSTNAME"] %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: dfe_wizard_development

test:
  <<: *default
  database: dfe_wizard_test
